services:

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  node_backend:
    build: ./server
    container_name: node_backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  py_backend:
    build: ./py_backend
    container_name: py_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:80"   # Frontend served on Nginx default port 80
    depends_on:
      - node_backend
      - py_backend

# Define volumes
volumes:
  mongo_data:

